### ISSUE TITLE
prefix relative src/href paths with `/`

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/mongoose-books-app#10]
All scripts and links should use paths relative to the _root_ (`/`) of the site. Otherwise scripts/stylesheets will be loaded from a relative path, e.g. `/example` (`/example/vendor/scripts/jQuery.js`)

See `index.html`

**Comment by mnfmnfm** [comment]
Now fixed in all branches. (what a good day to learn about `git cherry-pick`!)
